feat: slightly more helpful TaskError.__str__ (#99)
It actually wasn't as bad as I thought in #97, because the default
`Exception.__str__` is just the str of the args, so the traceback looked
like this:

```
jubilant._task.TaskError: Task(id='42', status='failed', ...)
```

However, this adds a human-readable first line, and pretty-dumps the
task dataclass:

```
jubilant._task.TaskError: task 42 failed with status 'failed' and return code 0
Task(
  id='42',
  status='failed',
  ...
)
```

Fixes #97